"use client";
import { motion } from "framer-motion";
import Link from "next/link";
import { ArrowRight, Brain, Target, TrendingUp, Zap, BarChart3, Map, HelpCircle } from "lucide-react";
import HeroParticleBackground from "@/components/HeroParticleBackground";

const features = [
  { icon: Brain,      title: "AI Readiness Assessment",  desc: "10 Agent-powered questions evaluate your true readiness for your target role." },
  { icon: Map,        title: "5-Month Roadmap",           desc: "Personalised month-by-month action plan with weekly milestones generated by AI." },
  { icon: BarChart3,  title: "Market Intelligence",       desc: "Live demand scores, salary ranges, and competitor analysis for your role." },
  { icon: Zap,        title: "Hands-On Mentoring",        desc: "Interactive AI mentor assigns and guides you through real practical tasks." },
  { icon: TrendingUp, title: "Confidence Tracking",       desc: "Dynamic score updates after every assessment to keep you calibrated." },
  { icon: Target,     title: "Smart Rerouting",           desc: "When confidence drops, AI suggests safer adjacent roles to rebuild momentum." },
];

const stats = [
  { value: "5-Month",   label: "Personalised Roadmap" },
  { value: "10 Agents", label: "Specialised AI Agents" },
  { value: "Real-Time", label: "Confidence Scoring" },
  { value: "100%",      label: "Server-side AI" },
];

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-[#0F1117] bg-grid overflow-hidden">
      <HeroParticleBackground />

      {/* Gradient orbs */}
      <div className="fixed top-0 left-1/4 w-96 h-96 bg-blue-600/10 rounded-full blur-3xl pointer-events-none" />
      <div className="fixed top-1/4 right-1/4 w-80 h-80 bg-violet-600/10 rounded-full blur-3xl pointer-events-none" />

      {/* Nav */}
      <nav className="fixed top-0 w-full z-50 glass border-b border-white/[0.06] backdrop-blur-xl">
        <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-blue-500 to-violet-600 flex items-center justify-center">
              <Brain size={16} className="text-white" />
            </div>
            <span className="font-bold text-lg tracking-tight">Nexus-AI</span>
          </div>
          <div className="flex items-center gap-3">
            <Link href="/help" className="btn-ghost text-sm py-2 px-4 flex items-center gap-1.5">
              <HelpCircle size={14} /> Help
            </Link>
            <Link href="/credits" className="btn-ghost text-sm py-2 px-4">Credits</Link>
            <Link href="/auth" className="btn-ghost text-sm py-2 px-4">Sign In</Link>
            <Link href="/auth" className="btn-primary text-sm py-2 px-4">Get Started</Link>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="pt-36 pb-24 px-6 max-w-7xl mx-auto text-center">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7 }}
        >
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-blue-500/10 border border-blue-500/20 text-blue-300 text-sm font-medium mb-8">
            <Zap size={13} />
            Powered by Agent · LLM-class Intelligence
          </div>

          <h1 className="text-5xl md:text-7xl font-black tracking-tight mb-6 leading-none">
            Your Agent Powered<br />
            <span className="gradient-text">Nexus-AI</span>
          </h1>

          <p className="text-xl text-white/50 max-w-2xl mx-auto mb-12 leading-relaxed">
            Nexus-AI deploys specialised agents to assess your readiness, map your journey,
            monitor your confidence, and reroute you when needed — all in real-time.
          </p>

          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link href="/auth" className="btn-primary inline-flex items-center gap-2 text-base px-8 py-4">
              Start Your Journey <ArrowRight size={18} />
            </Link>
            <Link href="#features" className="btn-ghost inline-flex items-center gap-2 text-base px-8 py-4">
              See How It Works
            </Link>
          </div>
        </motion.div>

        {/* Stats */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7, delay: 0.3 }}
          className="mt-20 grid grid-cols-2 md:grid-cols-4 gap-4"
        >
          {stats.map((s) => (
            <div key={s.label} className="glass p-6">
              <div className="text-3xl font-black gradient-text mb-1">{s.value}</div>
              <div className="text-sm text-white/40">{s.label}</div>
            </div>
          ))}
        </motion.div>
      </section>

      {/* Features */}
      <section id="features" className="py-24 px-6 max-w-7xl mx-auto">
        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <h2 className="text-4xl font-black mb-4">Six Specialised Agents</h2>
          <p className="text-white/40 text-lg">Each agent is an expert in its domain — working together seamlessly.</p>
        </motion.div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">
          {features.map((f, i) => (
            <motion.div
              key={f.title}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.08 }}
              className="card-glow p-6"
            >
              <div className="w-11 h-11 rounded-xl bg-gradient-to-br from-blue-500/20 to-violet-500/20 border border-blue-500/20 flex items-center justify-center mb-4">
                <f.icon size={20} className="text-blue-400" />
              </div>
              <h3 className="font-bold text-lg mb-2">{f.title}</h3>
              <p className="text-white/40 text-sm leading-relaxed">{f.desc}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="py-24 px-6">
        <motion.div
          initial={{ opacity: 0, scale: 0.96 }}
          whileInView={{ opacity: 1, scale: 1 }}
          viewport={{ once: true }}
          className="max-w-3xl mx-auto glass p-12 text-center shadow-glow"
        >
          <h2 className="text-4xl font-black mb-4">Ready to navigate smarter?</h2>
          <p className="text-white/40 mb-8">Join thousands using AI agents to accelerate their careers.</p>
          <Link href="/auth" className="btn-primary inline-flex items-center gap-2 text-base px-10 py-4">
            Begin Assessment <ArrowRight size={18} />
          </Link>
        </motion.div>
      </section>

      {/* Footer */}
      <footer className="border-t border-white/[0.06] py-8 px-6 text-center text-white/30 text-sm">
        <div className="flex items-center justify-center gap-4 mb-3">
          <Link href="/help" className="hover:text-white/60 transition-colors">Help</Link>
          <span>·</span>
          <Link href="/credits" className="hover:text-white/60 transition-colors">Credits</Link>
          <span>·</span>
          <a href="mailto:deepakthillaikannu@gmail.com" className="hover:text-white/60 transition-colors">Contact</a>
        </div>
        © 2026 Nexus-AI — Agentic Career Navigator
      </footer>
    </div>
  );
}
