"use client";
/**
 * roadmap/page.tsx
 * ─────────────────
 * Shows the 5-month roadmap accordion.
 * Each month has exactly 4 actions (generated by RoadmapAgent).
 * Clicking "Start Assessment" on a pending action opens AssessmentModal.
 * AssessmentModal calls:
 *   1. POST /api/action/questions  → ActionAssessmentAgent generates 10 questions
 *   2. User answers all 10 (1 per screen)
 *   3. POST /api/action/assess     → ActionAssessmentAgent evaluates, updates score + confidence
 * After submit the action card refreshes to show passed/failed + score.
 */
import { useEffect, useState, useCallback, Suspense } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { useSearchParams } from "next/navigation";
import {
  ChevronDown, ChevronRight, PlayCircle, CheckCircle2,
  XCircle, Clock, Loader2, ArrowLeft, X, Brain,
  ChevronLeft, AlertCircle,
} from "lucide-react";
import { getRoadmap, getActionQuestions, assessAction } from "@/lib/api";
import { useStore } from "@/store/useStore";
import ParticleBackground from "@/components/ParticleBackground";
import AIThinkingOverlay from "@/components/AIThinkingOverlay";

// ── Status badge ──────────────────────────────────────────────────
function StatusBadge({ status }: { status: string }) {
  if (status === "passed")
    return (
      <motion.span 
        initial={{ scale: 0.9 }}
        animate={{ scale: 1 }}
        className="badge-passed inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-emerald-500/20 text-emerald-400 font-semibold text-xs"
      >
        <CheckCircle2 size={14} /> Passed
      </motion.span>
    );
  if (status === "failed")
    return (
      <motion.span 
        initial={{ scale: 0.9 }}
        animate={{ scale: 1 }}
        className="badge-failed inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-red-500/20 text-red-400 font-semibold text-xs"
      >
        <XCircle size={14} /> Failed
      </motion.span>
    );
  return (
    <span className="badge-pending inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-orange-500/20 text-orange-400 font-semibold text-xs">
      <Clock size={14} /> Pending
    </span>
  );
}

// ── Assessment modal ─────────────────────────────────────────────
interface AssessmentModalProps {
  action:     { action_id: string; action_title: string };
  userId:     string;
  onClose:    () => void;
  onComplete: (result: any) => void;
}

function AssessmentModal({ action, userId, onClose, onComplete }: AssessmentModalProps) {
  type Phase = "loading" | "questions" | "submitting" | "result";
  const [phase,     setPhase]     = useState<Phase>("loading");
  const [questions, setQuestions] = useState<string[]>([]);
  const [answers,   setAnswers]   = useState<string[]>([]);
  const [current,   setCurrent]   = useState(0);
  const [draft,     setDraft]     = useState("");   // current textarea value
  const [result,    setResult]    = useState<any>(null);
  const [error,     setError]     = useState("");

  // Step 1 — fetch questions from ActionAssessmentAgent via backend
  useEffect(() => {
    setError("");
    getActionQuestions({ user_id: userId, action_id: action.action_id })
      .then((data) => {
        if (!data.questions || data.questions.length === 0) {
          setError("No questions returned. Please try again.");
          return;
        }
        setQuestions(data.questions);
        setAnswers(new Array(data.questions.length).fill(""));
        setPhase("questions");
      })
      .catch((e) => {
        setError(e.message || "Failed to load questions.");
      });
  }, []);

  // Save current draft into answers array, move forward
  function saveAndNext() {
    const upd = [...answers];
    upd[current] = draft;
    setAnswers(upd);
    setDraft(upd[current + 1] || "");
    setCurrent((c) => c + 1);
  }

  // Save current draft into answers array, move back
  function saveAndBack() {
    const upd = [...answers];
    upd[current] = draft;
    setAnswers(upd);
    setDraft(upd[current - 1] || "");
    setCurrent((c) => c - 1);
  }

  // Step 2 — submit all answers to ActionAssessmentAgent for evaluation
  async function handleSubmit() {
    const finalAnswers = [...answers];
    finalAnswers[current] = draft;
    setPhase("submitting");
    setError("");
    try {
      const res = await assessAction({
        user_id:    userId,
        action_id:  action.action_id,
        answers:    finalAnswers,
      });
      setResult(res);
      setPhase("result");
      onComplete(res);             // notify parent to refresh roadmap
    } catch (e: any) {
      setError(e.message || "Evaluation failed. Please try again.");
      setPhase("questions");
    }
  }

  const progress  = questions.length > 0 ? ((current + 1) / questions.length) * 100 : 0;
  const isLastQ   = current === questions.length - 1;
  const canSubmit = draft.trim().length > 0;

  return (
    <div className="fixed inset-0 bg-black/80 backdrop-blur-md z-50 flex items-center justify-center px-4 py-4">
      <motion.div
        initial={{ opacity: 0, scale: 0.92, y: 20 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.92, y: 20 }}
        transition={{ type: "spring", damping: 25, stiffness: 300 }}
        className="glass w-full max-w-2xl rounded-2xl overflow-hidden border border-white/[0.1]"
        style={{ maxHeight: "90vh", display: "flex", flexDirection: "column" }}
      >
        {/* Header */}
        <div className="p-6 border-b border-white/[0.06] flex items-start justify-between shrink-0 bg-gradient-to-r from-blue-500/[0.08] to-violet-500/[0.08]">
          <div className="flex items-center gap-4">
            <motion.div 
              animate={{ y: [0, -3, 0] }}
              transition={{ repeat: Infinity, duration: 2 }}
              className="w-11 h-11 rounded-xl bg-gradient-to-br from-blue-500 to-violet-600 flex items-center justify-center shadow-lg"
            >
              <Brain size={20} className="text-white" />
            </motion.div>
            <div>
              <p className="text-white/40 text-xs uppercase tracking-wider font-semibold">Action Assessment</p>
              <h3 className="font-bold text-lg leading-snug max-w-xl">{action.action_title}</h3>
            </div>
          </div>
          <motion.button 
            whileHover={{ scale: 1.1 }}
            whileTap={{ scale: 0.9 }}
            onClick={onClose} 
            className="text-white/40 hover:text-white/80 transition-colors p-2 rounded-lg hover:bg-white/[0.08]"
          >
            <X size={18} />
          </motion.button>
        </div>

        {/* Body — scrollable */}
        <div className="flex-1 overflow-y-auto p-6">

          {/* ── Phase: loading ── */}
          {phase === "loading" && !error && (
            <motion.div 
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="py-20 text-center"
            >
              <motion.div 
                animate={{ rotate: 360 }}
                transition={{ repeat: Infinity, duration: 2, ease: "linear" }}
                className="inline-block"
              >
                <Loader2 size={40} className="text-blue-400 mb-6" />
              </motion.div>
              <p className="text-white/60 font-semibold text-lg">Generating assessment questions</p>
              <p className="text-white/30 text-sm mt-2">The ActionAssessmentAgent is preparing 10 questions tailored to this action</p>
            </motion.div>
          )}

          {/* ── Phase: error ── */}
          {error && (
            <motion.div 
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              className="py-12 text-center space-y-4"
            >
              <div className="w-16 h-16 rounded-full bg-red-500/10 flex items-center justify-center mx-auto">
                <AlertCircle size={32} className="text-red-400" />
              </div>
              <div>
                <p className="text-red-400 font-semibold text-lg">{error}</p>
              </div>
              <motion.button 
                whileHover={{ scale: 1.05 }}
                onClick={onClose} 
                className="btn-ghost"
              >
                Close
              </motion.button>
            </motion.div>
          )}

          {/* ── Phase: questions ── */}
          {phase === "questions" && !error && (
            <motion.div 
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="space-y-6"
            >
              {/* Progress */}
              <div>
                <div className="flex justify-between text-xs text-white/40 mb-2 font-medium">
                  <span>Question {current + 1} of {questions.length}</span>
                  <span>{Math.round(progress)}% complete</span>
                </div>
                <div className="h-2 bg-white/[0.08] rounded-full overflow-hidden">
                  <motion.div
                    className="h-full bg-gradient-to-r from-blue-500 via-violet-500 to-pink-500 rounded-full"
                    animate={{ width: `${progress}%` }}
                    transition={{ duration: 0.4 }}
                  />
                </div>
              </div>

              {/* Question */}
              <AnimatePresence mode="wait">
                <motion.div
                  key={current}
                  initial={{ opacity: 0, x: 20 }}
                  animate={{ opacity: 1, x: 0 }}
                  exit={{ opacity: 0, x: -20 }}
                  transition={{ duration: 0.3 }}
                >
                  <p className="text-lg font-semibold leading-relaxed mb-5 text-white">
                    {questions[current]}
                  </p>
                  <div className="relative">
                    <textarea
                      value={draft}
                      onChange={(e) => setDraft(e.target.value)}
                      placeholder="Type your detailed answer here..."
                      rows={6}
                      className="input-field resize-none w-full bg-white/[0.04] border border-white/[0.1] rounded-xl focus:border-blue-500/50 focus:bg-white/[0.06] transition-colors"
                      autoFocus
                    />
                    <span className="text-xs text-white/30 absolute bottom-3 right-3">
                      {draft.length} characters
                    </span>
                  </div>
                </motion.div>
              </AnimatePresence>

              {/* Navigation */}
              <div className="flex justify-between gap-3 pt-2">
                <motion.button
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                  onClick={saveAndBack}
                  disabled={current === 0}
                  className="btn-ghost flex items-center gap-2 disabled:opacity-30 disabled:pointer-events-none rounded-lg"
                >
                  <ChevronLeft size={16} /> Back
                </motion.button>

                {isLastQ ? (
                  <motion.button
                    whileHover={{ scale: 1.05 }}
                    whileTap={{ scale: 0.95 }}
                    onClick={handleSubmit}
                    disabled={!canSubmit}
                    className="btn-primary flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed rounded-lg"
                  >
                    <CheckCircle2 size={16} /> Submit Answers
                  </motion.button>
                ) : (
                  <motion.button
                    whileHover={{ scale: 1.05 }}
                    whileTap={{ scale: 0.95 }}
                    onClick={saveAndNext}
                    disabled={!canSubmit}
                    className="btn-primary flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed rounded-lg"
                  >
                    Next <ChevronRight size={16} />
                  </motion.button>
                )}
              </div>
            </motion.div>
          )}

          {/* ── Phase: submitting ── */}
          {phase === "submitting" && (
            <motion.div 
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="py-20 text-center"
            >
              <motion.div 
                animate={{ rotate: 360 }}
                transition={{ repeat: Infinity, duration: 2, ease: "linear" }}
                className="inline-block mb-6"
              >
                <Loader2 size={40} className="text-violet-400" />
              </motion.div>
              <p className="text-white/60 font-semibold text-lg">Evaluating your answers</p>
              <p className="text-white/30 text-sm mt-2">The ActionAssessmentAgent is analyzing your responses and calculating your score</p>
            </motion.div>
          )}

          {/* ── Phase: result ── */}
          {phase === "result" && result && (
            <motion.div 
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              className="py-8 text-center space-y-6"
            >
              {/* Big score */}
              <div>
                <p className="text-white/40 text-sm font-medium mb-3">Your Assessment Score</p>
                <motion.div
                  initial={{ scale: 0.5, opacity: 0 }}
                  animate={{ scale: 1, opacity: 1 }}
                  transition={{ type: "spring", damping: 12, stiffness: 200, delay: 0.1 }}
                  className={`text-8xl font-black mb-2 ${result.passed ? "text-emerald-400" : "text-red-400"}`}
                >
                  {result.score}
                </motion.div>
                <span className="text-white/30 text-sm font-medium">out of 100</span>
              </div>

              {/* Pass / fail badge */}
              <motion.div 
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.2 }}
                className={`inline-flex items-center gap-3 px-6 py-3 rounded-xl font-bold text-sm
                  ${result.passed
                    ? "bg-emerald-500/15 text-emerald-400 border border-emerald-500/30"
                    : "bg-red-500/15 text-red-400 border border-red-500/30"}`}
              >
                {result.passed
                  ? <><CheckCircle2 size={18} /> Action Passed</>
                  : <><XCircle size={18} /> Action Failed</>
                }
              </motion.div>

              {/* Confidence change */}
              <motion.div 
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.3 }}
                className="glass border border-white/[0.08] p-4 rounded-xl"
              >
                <p className="text-white/40 text-xs mb-2 uppercase tracking-wider">Confidence Updated</p>
                <div className="flex items-center justify-center gap-2">
                  <span className="text-3xl font-black text-blue-400">{result.updated_confidence_score}</span>
                  <span className="text-white/40">confidence score</span>
                </div>
              </motion.div>

              {/* Summary */}
              <motion.p 
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 0.25 }}
                className="text-white/50 text-sm leading-relaxed max-w-lg mx-auto"
              >
                {result.evaluation_summary}
              </motion.p>

              {/* Reroute warning if triggered */}
              {result.reroute_check?.reroute_suggestion && (
                <motion.div 
                  initial={{ opacity: 0, x: -10 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: 0.35 }}
                  className="glass border border-orange-500/25 p-4 rounded-xl text-sm text-orange-300 text-left"
                >
                  <strong className="block mb-1">⚠️ Suggested Reroute</strong>
                  <p>{result.reroute_check.reason}</p>
                </motion.div>
              )}

              <motion.button 
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 0.4 }}
                onClick={onClose} 
                className="btn-primary px-12 py-3 rounded-lg mt-4"
              >
                Done
              </motion.button>
            </motion.div>
          )}
        </div>
      </motion.div>
    </div>
  );
}

// ── Main page ────────────────────────────────────────────────────
export default function RoadmapPage() {
  return <Suspense fallback={<div className="min-h-screen flex items-center justify-center bg-[#0F1117]"><Loader2 size={28} className="animate-spin text-blue-400" /></div>}><RoadmapPageInner /></Suspense>;
}

function RoadmapPageInner() {
  const params   = useSearchParams();
  const storeUid = useStore((s) => s.userId);
  const userId   = params.get("uid") || storeUid || "";

  const [roadmap,    setRoadmap]    = useState<any>(null);
  const [loading,    setLoading]    = useState(true);
  const [openMonth,  setOpenMonth]  = useState<number | null>(1);  // month 1 open by default
  const [assessing,  setAssessing]  = useState<any>(null);         // action being assessed
  const [showOverlay, setShowOverlay] = useState(true);

  const fetchRoadmap = useCallback(() => {
    if (!userId) return;
    getRoadmap(userId)
      .then((d) => { setRoadmap(d); setLoading(false); })
      .catch((e) => { console.error(e); setLoading(false); });
  }, [userId]);

  useEffect(() => { fetchRoadmap(); }, [fetchRoadmap]);

  // After assessment completes, close modal + refresh roadmap data
  function handleComplete(_result: any) {
    setAssessing(null);
    fetchRoadmap();
  }

  if (loading) return (
    <div className="min-h-screen flex items-center justify-center bg-[#0F1117]">
      <Loader2 size={28} className="animate-spin text-blue-400" />
    </div>
  );

  const steps: any[] = roadmap?.roadmap?.steps || [];
  const totalActions = steps.reduce((n: number, s: any) => n + s.actions.length, 0);
  const doneActions  = steps.reduce((n: number, s: any) =>
    n + s.actions.filter((a: any) => a.status !== "pending").length, 0);
  const overallPct   = totalActions > 0 ? Math.round((doneActions / totalActions) * 100) : 0;

  return (
    <div className="min-h-screen bg-[#0F1117] bg-grid">
      <ParticleBackground />
      <AIThinkingOverlay 
        visible={showOverlay} 
        onComplete={() => setShowOverlay(false)} 
        duration={5000}
        subtitle="Planning"
        messages={[
          "Analyzing your target role...",
          "Mapping skill gaps...",
          "Setting milestone targets...",
          "Structuring action plans...",
          "Generating your roadmap...",
        ]}
      />
      {!showOverlay && (
      <>
      {/* Assessment modal — rendered on top when an action is selected */}
      {assessing && (
        <AssessmentModal
          action={assessing}
          userId={userId}
          onClose={() => setAssessing(null)}
          onComplete={handleComplete}
        />
      )}

      <main className="max-w-5xl mx-auto px-6 py-12">

        {/* Page header */}
        <motion.div 
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="mb-10"
        >
          <div className="flex items-center gap-3 mb-6">
            <button onClick={() => window.history.back()} className="btn-ghost p-2 hover:bg-white/[0.08] transition-colors rounded-lg">
              <ArrowLeft size={18} />
            </button>
            <div className="flex-1 min-w-0">
              <h1 className="text-4xl font-black bg-gradient-to-r from-blue-400 to-violet-400 bg-clip-text text-transparent">
                5-Month Roadmap
              </h1>
              <div className="flex flex-col sm:flex-row sm:items-center gap-2 mt-2">
                <p className="text-white/50 text-sm">
                  Target role: <span className="text-white/70 font-semibold">{roadmap?.roadmap?.generated_for_role || "—"}</span>
                </p>
                <span className="hidden sm:block text-white/20">·</span>
                <p className="text-white/50 text-sm">
                  System confidence: <span className={`font-bold ${roadmap?.confidence_score >= 70 ? 'text-emerald-400' : roadmap?.confidence_score >= 40 ? 'text-yellow-400' : 'text-orange-400'}`}>
                    {roadmap?.confidence_score ?? 0}%
                  </span>
                </p>
              </div>
            </div>
          </div>

          {/* Overall progress card */}
          <div className="glass p-5 rounded-2xl border border-white/[0.08]">
            <div className="flex items-center justify-between mb-3">
              <span className="text-white/60 text-sm font-medium">Overall Progress</span>
              <span className="text-lg font-bold text-blue-400">{doneActions}/{totalActions}</span>
            </div>
            <div className="h-2.5 bg-white/[0.05] rounded-full overflow-hidden">
              <motion.div
                className="h-full bg-gradient-to-r from-blue-500 via-violet-500 to-pink-500 rounded-full"
                initial={{ width: 0 }}
                animate={{ width: `${overallPct}%` }}
                transition={{ duration: 0.8, ease: "easeOut" }}
              />
            </div>
            <div className="mt-3 flex items-center justify-between">
              <span className="text-xs text-white/40">{overallPct}% completed</span>
              <span className="text-xs text-white/40">{totalActions - doneActions} actions remaining</span>
            </div>
          </div>
        </motion.div>

        {/* Roadmap steps accordion */}
        {steps.length === 0 ? (
          <motion.div 
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className="glass p-16 text-center rounded-2xl border border-white/[0.08]"
          >
            <div className="w-16 h-16 rounded-2xl bg-blue-500/10 flex items-center justify-center mx-auto mb-4">
              <AlertCircle className="text-blue-400" size={24} />
            </div>
            <p className="text-white/50 font-medium">No roadmap generated yet</p>
            <p className="text-white/30 text-sm mt-2">Complete the readiness assessment first to generate your personalized 5-month roadmap.</p>
          </motion.div>
        ) : (
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ staggerChildren: 0.1, delayChildren: 0.2 }}
            className="space-y-3"
          >
            {steps.map((step: any, stepIdx: number) => {
              const isOpen    = openMonth === step.month;
              const actions: any[] = step.actions || [];
              const passedN   = actions.filter((a) => a.status === "passed").length;
              const failedN   = actions.filter((a) => a.status === "failed").length;
              const totalN    = actions.length;
              const pct       = totalN > 0 ? Math.round((passedN / totalN) * 100) : 0;
              const allDone   = passedN + failedN === totalN && totalN > 0;

              return (
                <motion.div 
                  key={step.month}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: stepIdx * 0.1 }}
                  className={`overflow-hidden rounded-xl transition-all duration-300
                    ${allDone 
                      ? "card-glow bg-gradient-to-br from-emerald-500/5 to-teal-500/5 border border-emerald-500/20" 
                      : "card-glow border border-white/[0.08] hover:border-white/[0.12]"}`}
                >

                  {/* Month accordion header */}
                  <button
                    className="w-full flex items-center justify-between p-6 text-left hover:bg-white/[0.02] transition-colors"
                    onClick={() => setOpenMonth(isOpen ? null : step.month)}
                  >
                    <div className="flex items-center gap-4 flex-1 min-w-0">
                      {/* Month badge */}
                      <motion.div
                        animate={{ scale: isOpen ? 1.1 : 1 }}
                        className={`w-14 h-14 rounded-xl flex items-center justify-center text-lg font-black shadow-glow shrink-0
                          ${allDone
                            ? "bg-gradient-to-br from-emerald-500 to-teal-600"
                            : "bg-gradient-to-br from-blue-500 to-violet-600"}`}
                      >
                        {allDone ? <CheckCircle2 size={20} /> : step.month}
                      </motion.div>
                      
                      {/* Month info */}
                      <div className="flex-1 min-w-0">
                        <h3 className="font-bold text-lg leading-tight">{step.step_title}</h3>
                        <div className="flex flex-wrap gap-3 mt-2">
                          <span className="text-xs text-emerald-400 font-semibold flex items-center gap-1">
                            <CheckCircle2 size={12} />
                            {passedN} passed
                          </span>
                          {failedN > 0 && (
                            <span className="text-xs text-red-400 font-semibold flex items-center gap-1">
                              <XCircle size={12} />
                              {failedN} failed
                            </span>
                          )}
                          <span className="text-xs text-white/40">{totalN} total actions</span>
                        </div>
                      </div>
                    </div>

                    {/* Progress bar + chevron */}
                    <div className="flex items-center gap-4 shrink-0 ml-4">
                      {/* Circular progress indicator */}
                      <div className="flex flex-col items-end gap-1">
                        <div className="relative w-12 h-12 rounded-full bg-white/[0.03] flex items-center justify-center border border-white/[0.06]">
                          <div className="absolute inset-1 rounded-full overflow-hidden">
                            <svg className="w-full h-full transform -rotate-90" viewBox="0 0 100 100">
                              <circle cx="50" cy="50" r="45" fill="none" stroke="currentColor" strokeWidth="2" className="text-white/[0.08]" />
                              <motion.circle
                                cx="50" cy="50" r="45"
                                fill="none"
                                stroke="currentColor"
                                strokeWidth="2"
                                className={allDone ? "text-emerald-500" : "text-violet-500"}
                                strokeDasharray={`${2 * Math.PI * 45}`}
                                initial={{ strokeDashoffset: `${2 * Math.PI * 45}` }}
                                animate={{ strokeDashoffset: `${2 * Math.PI * 45 * (1 - pct / 100)}` }}
                                transition={{ duration: 0.6 }}
                              />
                            </svg>
                          </div>
                          <span className={`text-xs font-bold tabular-nums ${allDone ? "text-emerald-400" : "text-white/50"}`}>
                            {pct}%
                          </span>
                        </div>
                      </div>

                      <motion.div
                        animate={{ rotate: isOpen ? 180 : 0 }}
                        transition={{ duration: 0.2 }}
                        className="text-white/40"
                      >
                        <ChevronDown size={20} />
                      </motion.div>
                    </div>
                  </button>

                  {/* Actions list — shown when month is open */}
                  <AnimatePresence initial={false}>
                    {isOpen && (
                      <motion.div
                        key="content"
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: "auto", opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        transition={{ duration: 0.3 }}
                        className="overflow-hidden border-t border-white/[0.06]"
                      >
                        <div className="px-6 py-4 space-y-3 bg-white/[0.01]">
                          {actions.map((action: any, idx: number) => (
                            <motion.div
                              key={action.action_id}
                              initial={{ opacity: 0, x: -10 }}
                              animate={{ opacity: 1, x: 0 }}
                              transition={{ delay: idx * 0.05 }}
                              className={`flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-4
                                rounded-xl backdrop-blur-sm transition-all duration-200
                                ${action.status === "passed"
                                  ? "bg-emerald-500/[0.08] border border-emerald-500/25 hover:border-emerald-500/40 hover:bg-emerald-500/[0.12]"
                                : action.status === "failed"
                                  ? "bg-red-500/[0.08] border border-red-500/25 hover:border-red-500/40 hover:bg-red-500/[0.12]"
                                  : "bg-white/[0.04] border border-white/[0.1] hover:border-white/[0.15] hover:bg-white/[0.06]"}`}
                            >
                              {/* Left side — action info */}
                              <div className="flex items-start gap-4 flex-1 min-w-0">
                                {/* Week circle with improved styling */}
                                <div className={`w-10 h-10 rounded-lg flex items-center justify-center text-sm font-bold shrink-0 mt-0.5 shadow-md
                                  ${action.status === "passed" 
                                    ? "bg-gradient-to-br from-emerald-500 to-teal-600 text-white"
                                    : action.status === "failed" 
                                    ? "bg-gradient-to-br from-red-500 to-rose-600 text-white"
                                    : "bg-gradient-to-br from-blue-500/40 to-violet-500/40 text-blue-200"}`}>
                                  W{action.week}
                                </div>
                                
                                {/* Action title */}
                                <div className="min-w-0 flex-1">
                                  <p className="text-sm font-semibold leading-snug text-white">{action.action_title}</p>
                                </div>
                              </div>

                              {/* Right side — score + badge + button */}
                              <div className="flex items-center gap-3 shrink-0 sm:ml-3">
                                {action.score != null && (
                                  <motion.span 
                                    initial={{ scale: 0.9 }}
                                    animate={{ scale: 1 }}
                                    className={`text-sm font-black tabular-nums px-3 py-1.5 rounded-lg
                                      ${action.status === "passed" 
                                        ? "bg-emerald-500/20 text-emerald-400" 
                                        : "bg-red-500/20 text-red-400"}`}
                                  >
                                    {action.score}<span className="text-white/40 text-xs font-normal ml-0.5">/100</span>
                                  </motion.span>
                                )}
                                
                                <StatusBadge status={action.status} />
                                
                                {/* Assess button for pending actions */}
                                {action.status === "pending" && (
                                  <motion.button
                                    whileHover={{ scale: 1.05 }}
                                    whileTap={{ scale: 0.95 }}
                                    onClick={() => setAssessing(action)}
                                    className="btn-primary text-xs py-2 px-3.5 flex items-center gap-1.5 rounded-lg"
                                  >
                                    <PlayCircle size={12} />
                                    Start
                                  </motion.button>
                                )}
                              </div>
                            </motion.div>
                          ))}
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </motion.div>
              );
            })}
          </motion.div>
        )}

        {/* Bottom summary */}
        {steps.length > 0 && (
          <motion.div 
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.4 }}
            className="glass mt-8 p-6 rounded-2xl border border-white/[0.08] bg-gradient-to-r from-blue-500/[0.05] to-violet-500/[0.05]"
          >
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
              <div>
                <p className="text-white/40 text-sm font-medium mb-2">Roadmap Completion</p>
                <p className="text-2xl font-black gradient-text">{doneActions}/{totalActions} Actions Complete</p>
              </div>
              <div className="flex items-center gap-4">
                <div className="text-right">
                  <p className="text-white/40 text-xs mb-1">Progress</p>
                  <p className={`text-3xl font-black ${overallPct === 100 ? 'text-emerald-400' : overallPct >= 50 ? 'text-blue-400' : 'text-yellow-400'}`}>
                    {overallPct}%
                  </p>
                </div>
                <div className="w-16 h-16 relative">
                  <svg className="w-full h-full transform -rotate-90" viewBox="0 0 100 100">
                    <circle cx="50" cy="50" r="45" fill="none" stroke="currentColor" strokeWidth="3" className="text-white/[0.1]" />
                    <motion.circle
                      cx="50" cy="50" r="45"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="3"
                      className={overallPct === 100 ? "text-emerald-400" : "text-blue-400"}
                      strokeDasharray={`${2 * Math.PI * 45}`}
                      initial={{ strokeDashoffset: `${2 * Math.PI * 45}` }}
                      animate={{ strokeDashoffset: `${2 * Math.PI * 45 * (1 - overallPct / 100)}` }}
                      transition={{ duration: 1 }}
                      strokeLinecap="round"
                    />
                  </svg>
                </div>
              </div>
            </div>
          </motion.div>
        )}
      </main>
      </>
      )}
    </div>
  );
}
